export interface Country {
  code: string;
  flag: string;
  label: string;
}

export const COUNTRIES: Country[] = [
  { code: "US", flag: "🇺🇸", label: "США" },
  { code: "GB", flag: "🇬🇧", label: "Великобритания" },
  { code: "DE", flag: "🇩🇪", label: "Германия" },
  { code: "FR", flag: "🇫🇷", label: "Франция" },
  { code: "CA", flag: "🇨🇦", label: "Канада" },
  { code: "AU", flag: "🇦🇺", label: "Австралия" },
  { code: "JP", flag: "🇯🇵", label: "Япония" },
  { code: "KR", flag: "🇰🇷", label: "Южная Корея" },
  { code: "CN", flag: "🇨🇳", label: "Китай" },
  { code: "SG", flag: "🇸🇬", label: "Сингапур" },
  { code: "NL", flag: "🇳🇱", label: "Нидерланды" },
  { code: "CH", flag: "🇨🇭", label: "Швейцария" },
  { code: "SE", flag: "🇸🇪", label: "Швеция" },
  { code: "NO", flag: "🇳🇴", label: "Норвегия" },
  { code: "FI", flag: "🇫🇮", label: "Финляндия" },
  { code: "DK", flag: "🇩🇰", label: "Дания" },
  { code: "AT", flag: "🇦🇹", label: "Австрия" },
  { code: "BE", flag: "🇧🇪", label: "Бельгия" },
  { code: "IT", flag: "🇮🇹", label: "Италия" },
  { code: "ES", flag: "🇪🇸", label: "Испания" },
  { code: "PT", flag: "🇵🇹", label: "Португалия" },
  { code: "PL", flag: "🇵🇱", label: "Польша" },
  { code: "CZ", flag: "🇨🇿", label: "Чехия" },
  { code: "HU", flag: "🇭🇺", label: "Венгрия" },
  { code: "TR", flag: "🇹🇷", label: "Турция" },
  { code: "AE", flag: "🇦🇪", label: "ОАЭ" },
  { code: "QA", flag: "🇶🇦", label: "Катар" },
  { code: "IL", flag: "🇮🇱", label: "Израиль" },
  { code: "IN", flag: "🇮🇳", label: "Индия" },
  { code: "MY", flag: "🇲🇾", label: "Малайзия" },
  { code: "TH", flag: "🇹🇭", label: "Таиланд" },
  { code: "HK", flag: "🇭🇰", label: "Гонконг" },
  { code: "TW", flag: "🇹🇼", label: "Тайвань" },
  { code: "NZ", flag: "🇳🇿", label: "Новая Зеландия" },
  { code: "IE", flag: "🇮🇪", label: "Ирландия" },
  { code: "RU", flag: "🇷🇺", label: "Россия" },
  { code: "KZ", flag: "🇰🇿", label: "Казахстан" },
  { code: "UZ", flag: "🇺🇿", label: "Узбекистан" },
  { code: "KG", flag: "🇰🇬", label: "Кыргызстан" },
  { code: "GE", flag: "🇬🇪", label: "Грузия" },
  { code: "EE", flag: "🇪🇪", label: "Эстония" },
  { code: "LV", flag: "🇱🇻", label: "Латвия" },
  { code: "LT", flag: "🇱🇹", label: "Литва" },
  { code: "BR", flag: "🇧🇷", label: "Бразилия" },
  { code: "MX", flag: "🇲🇽", label: "Мексика" },
  { code: "AR", flag: "🇦🇷", label: "Аргентина" },
  { code: "CL", flag: "🇨🇱", label: "Чили" },
  { code: "ZA", flag: "🇿🇦", label: "ЮАР" },
  { code: "EG", flag: "🇪🇬", label: "Египет" },
  { code: "NG", flag: "🇳🇬", label: "Нигерия" },
];
